spring.application.name=boxcorner
spring.datasource.url=jdbc:postgresql://dpg-d4e6v1qdbo4c73daujr0-a.singapore-postgres.render.com:5432/uat_boxcorner?currentSchema=uat
spring.datasource.username=uat_boxcorner_user
spring.datasource.password=IfekRGja3BhNxTcGoipcnh61bC4MCggz
