# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d4e6v1qdbo4c73daujr0-a.singapore-postgres.render.com:5432/uat_boxcorner?currentSchema=uat
spring.datasource.username=uat_boxcorner_user
spring.datasource.password=IfekRGja3BhNxTcGoipcnh61bC4MCggz
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080